### ISSUE TITLE
How to handle media queries?

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/atomify#1]
@chrisjames-work raised a very interesting and tricky scenario which are media queries. How to isolate a pattern that has multiple media query rules (and still make sense)?

``` css
.container {
  width: 100%;
  padding: 3rem;

  @media (min-width: 800px) {
    width: 50%;
  }
}

.full-width {
  width: 100%;

  @media (min-width: 800px) {
    width: 90%;
  }
}
```
