### ISSUE TITLE
Integrating with webpack

### ISSUE THREAD

**Issue by mauriciosoares** [rafaelrinaldi/atomify#4]
I may be overthinking about this, but it's nice to already have some thoughts about building tools (and as webpack is probably one of the most famous nowadays..)

Let's say I wan't to use this approach with webpack's css/style plugins... we could do something like this:

``` css
.container {
  width: 100%;
  padding: 3rem;
}

.full-width {
  width: 100%;
}
```

``` js
import styles from './index.scss';

styles.container; // this would output `container _15QFk`
styles['full-width']; // this would output `_15QFk`
```

In case of `container`, it returns both classes... and in `full-width` as it becomes empty, it only returns the generated class by atomify.

This is particularly useful in react.js projects, as we use the classes as variables.
