### ISSUE TITLE
Initial thoughts²

### ISSUE THREAD

**Issue by filipelinhares** [rafaelrinaldi/atomify#5]
I see as a very good tool for code refactoring. Use it in a code that does not use css atomic but will use, would be very handy.
### Is a build tool a good way to approach this?

Yes, would be great to have a tool to do it.

Have some options that I think would be nice to have:
- Other naming conventions to the atomic css generated.
- Pre-processors support?
- The option to atomify just selected properties.
### How to generate a proper report for the compiled file?

We can group related properties in section (with comments) or different files.

``` css
/* atomic/layout.css */

.fl { float: left; }
.db { display: block; }
```

or:

``` css
/* atomic/float.css */

.fl { float: left; }
.fr { float: right; }
```
### How to handle media queries?

The input:

``` css
.container {
  width: 100%;
  padding: 3rem;
}

.full-width {
  width: 100%;
}

@media (min-width: 60em) {
  .container {
    width: 90%;
  }

  .full-width {
    width: 90%;
  }
}
```

The output:

``` css
.container {
  padding: 3rem;
}

.w100 {
  width: 100%;
}

@media (min-width: 60em) {
  .m60-w90 {
    width: 90%;
  }
}
```
### How to sync dev vs. prod markup?

I think atomify don't need to care about markup.
### Related tools

How does other projects are dealing with the atomic CSS approach?
- [acss.io](http://acss.io)
